# -*- coding: utf-8 -*-
User.create(:email => 'bognerth@gmail.com', :password => 'la+ja+no', :password_confirmation => 'la+ja+no')
Group.create(name: "Lehrer")
Group.create(name: "FIT1AF")
Group.create(name: "FIT1H")
Student.create(user_id: 1,group_id: 1)
Category.create(name: "Category Test")
Category.create(name: "Linux Shell Teil 1")
Category.create(name: "Linux Shell Teil 2")
Category.create(name: "Linux Systemadministration")
Category.create(name: "Linux Server")
Course.create(name: "Fit1AF KuA ", group_id: 2)
Course.create(name: "Fit1H KuA", group_id: 3)
Test.create(description: "Test Shell November Kurs 1",course_id: 1,category_id: 1, duration: 10)
Test.create(description: "FIT1AF Shell 1 - Dezember",course_id: 1,category_id: 2, duration: 20)
Test.create(description: "FIT1H Shell 1  - Dezember",course_id: 2,category_id: 2, duration: 20)
Test.create(description: "FIT1AF Shell 2 - Januar 2013", course_id: 1, category_id: 3, duration: 20)
Test.create(description: "FIT1H Shell 2 - Januar 2013", course_id: 2, category_id: 3, duration: 20)
TestEvent.create(test_id: 1, state: "open")
TestEvent.create(test_id: 2, state: "new")
TestEvent.create(test_id: 3, state: "new")
TestEvent.create(test_id: 4, state: "new")
TestEvent.create(test_id: 5, state: "new")

